version: "3"

services:
  app:
    image: bc_app
    container_name: bc_app
    build:
      context: .
      dockerfile: "dev.Dockerfile"
    restart: always
    depends_on:
      - db
    ports:
      - "4000:4000"
      - "2345:2345" #デバッグ用のポート
    volumes:   # Dockerfile.prodを起動させたい場合はコメントアウト
      - .:/bc_app # ローカルとコンテナのディレクトリをバインドマウント（同期）
  db:
    image: bc_db
    container_name: bc_db
    build: ./mysql/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bc_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    ports:
      - "3308:3306"
    volumes:
      - test-volume:/var/lib/mysql

volumes:
  test-volume:
