// Code generated by MockGen. DO NOT EDIT.
// Source: ./I_auth_repository.go

// Package mock_authusecase is a generated GoMock package.
package mock_authusecase

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/toshi0228/blockchain/src/entity"
	input "github.com/toshi0228/blockchain/src/usecase/authusecase/input"
)

// MockIAuthRepository is a mock of IAuthRepository interface.
type MockIAuthRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIAuthRepositoryMockRecorder
}

// MockIAuthRepositoryMockRecorder is the mock recorder for MockIAuthRepository.
type MockIAuthRepositoryMockRecorder struct {
	mock *MockIAuthRepository
}

// NewMockIAuthRepository creates a new mock instance.
func NewMockIAuthRepository(ctrl *gomock.Controller) *MockIAuthRepository {
	mock := &MockIAuthRepository{ctrl: ctrl}
	mock.recorder = &MockIAuthRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAuthRepository) EXPECT() *MockIAuthRepositoryMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockIAuthRepository) Login(in *input.LoginInput) (*entity.UserPager, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", in)
	ret0, _ := ret[0].(*entity.UserPager)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockIAuthRepositoryMockRecorder) Login(in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockIAuthRepository)(nil).Login), in)
}

// SignUp mocks base method.
func (m *MockIAuthRepository) SignUp(in *input.SignUpInput) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignUp", in)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignUp indicates an expected call of SignUp.
func (mr *MockIAuthRepositoryMockRecorder) SignUp(in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignUp", reflect.TypeOf((*MockIAuthRepository)(nil).SignUp), in)
}
